/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=worker/wrangler.toml --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings worker/src/bindings.d.ts` (hash: 6919e9fe2b943fa0e5af3215099c5365)
interface __BaseEnv_CloudflareBindings {
	OAUTH_KV: KVNamespace;
	DB: D1Database;
	MCP_RATE_LIMITER: RateLimit;
	MCP_WEEKLY_TOOL_LIMIT: string;
	MCP_MONTHLY_TOOL_LIMIT: string;
	MCP_PUBLIC_URL: string;
	APP_ORIGIN: string;
	WORKOS_CLIENT_ID: string;
	MCP_USAGE: DurableObjectNamespace<import("./index").McpUsage>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "McpUsage";
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MCP_WEEKLY_TOOL_LIMIT" | "MCP_MONTHLY_TOOL_LIMIT" | "MCP_PUBLIC_URL" | "APP_ORIGIN" | "WORKOS_CLIENT_ID">> {}
}
