let p = document.querySelector("main > div > div > div > div")
let c = p.children
// loop through c to see if they are p elements or pre elements
let page = []
let first_time = true
function saveChildInnerHTML(parent, clone=true) { // generated by ChatGPT
    // Get the child elements of the parent
    let p1;
    if (clone) {
        p1 = parent.cloneNode(true)
        p1.setAttribute("style", "display: none;");
        document.body.appendChild(p1);
    }
    else{
        p1 = parent
    }
    var children = p1.children;

    // Create a string to store the innerHTML of each child
    var childInnerHTML = '';

    // Loop through each child element
    for (var i = 0; i < children.length; i++) {
        // Clone the child element
        var child = children[i];
        if (child.tagName == "PRE") {
            let text = child.firstChild.children[1].outerHTML
            let template = `<pre>${text}</pre><br>`
            console.log(template)
            childInnerHTML += template;
        }
        else {
            // Remove the child's class attribute
            child.removeAttribute("class");

            // Recursively call the function on the child's children
            saveChildInnerHTML(child, false);

            // Add the child's innerHTML to the string
            childInnerHTML += child.outerHTML;
        }
    }

    return childInnerHTML;
}



function save_thread(human, h) {
    if(human){
        let text = h.innerText // saves as plain text
        page.push(text)
    }
    if(!human){
        let text = saveChildInnerHTML(h.firstChild.children[1].firstChild.firstChild) // saves as html
        page.push(text)
    }
}
function getDate() { // generated by ChatGPT
    var date = new Date();
    var options = { year: 'numeric', month: 'long', day: 'numeric' };
    return date.toLocaleString('default', options);
}
function getTime(){ // generated by ChatGPT
    var currentDate = new Date();
    var options = {
        hour12: true,
        hour: "numeric",
        minute: "numeric"
    };
    var timeString = currentDate.toLocaleTimeString("default", options);
    return timeString
}

function save_page(){
    page = []
    for(let i = 0; i < c.length - 1; i++){
        let human = i % 2 === 0;
        save_thread(human, c[i])
    }
    let thread = {date: getDate(), time: getTime(), convo: page, favorite: false}
    chrome.storage.local.get({threads: null}).then((result) => {
        let t = result.threads
        if (t !== null) {
            let t = result.threads
            if (first_time) {
                t.push(thread)
                first_time = false
            }
            else {
                t[t.length - 1] = thread
            }
            chrome.storage.local.set({threads: t})
        }
        else {
            let t = [page]
            chrome.storage.local.set({threads: t})
        }
    });}

document.addEventListener('keydown', function(event) { // generated by ChatGPT
    // Check if the pressed key was the Enter key
    if (event.key === 'Enter') {
        setTimeout(save_page, 500)
    }
});

let main = p
var interval;
main.addEventListener('DOMSubtreeModified', function() { // generated by ChatGPT
    clearInterval(interval)
    interval = setInterval(function() {
        save_page()
    }, 7000);

    setTimeout(function() {
        clearInterval(interval);
    }, 80000);

});
let reset = document.querySelector("nav").firstChild
reset.addEventListener('click', function() {
    first_time = true
})