name: Schedule script execution

on:
  schedule:
    - cron: '55 12 1 5 *'  # Run the script at 12:55 (6:55 AM MDT) on May 1st

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          chmod +x update_ad.sh
          ./update_ad.sh
