name: Schedule script execution

on:
  schedule:
    - cron: '50 13 * * *'  # Run the script every day at 6:50 AM MST

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          chmod +x update_ad.sh
          ./update_ad.sh
