name: Schedule script execution

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '01 4 * * *'  # Run the script every day 

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          chmod +x update_ad.sh
          ./update_ad.sh
